apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  envs:
  - environment-values.env
  name: iec-plan-optimizer-environment-values
- behavior: merge
  envs:
  - container.env
  name: iec-plan-optimizer-container-vars
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/name: iec-plan-optimizer
    app.kubernetes.io/version: ""
namespace: prod
resources:
- ../../base
images:
- name: ghcr.io/skyhook-io/iec-plan-optimizer
