apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - ingress.yaml

namePrefix: prod-

images:
  - name: ghcr.io/skyhook-io/iec-plan-optimizer
    newTag: v1.0.0

replicas:
  - name: iec-plan-optimizer
    count: 2
