apiVersion: apps/v1
kind: Deployment
metadata:
  name: iec-plan-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iec-plan-optimizer
  template:
    spec:
      serviceAccountName: iec-plan-optimizer
      imagePullSecrets:
      - name: ghcr-image-pull-secret
      containers:
      - name: iec-plan-optimizer
        image: ghcr.io/skyhook-io/iec-plan-optimizer:latest
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: iec-plan-optimizer-container-vars
    metadata:
      labels:
        app.kubernetes.io/name: iec-plan-optimizer
