apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: iec-plan-optimizer-environment-values
  envs:
  - environment-values.env
- name: iec-plan-optimizer-container-vars
  envs:
  - container.env
generatorOptions:
  disableNameSuffixHash: true # use a static name
labels:
- pairs:
    app: iec-plan-optimizer
    app.kubernetes.io/name: iec-plan-optimizer
    app.kubernetes.io/part-of: iec-plan-optimizer
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
